spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: workspace-service

  datasource:
    url: ${SYSTEMLENS_DB_URL}
    username: ${SYSTEMLENS_DB_USERNAME}
    password: ${SYSTEMLENS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info
